# Generated by Django 2.2.4 on 2019-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Фото'),
        ),
    ]
