# Generated by Django 2.2.4 on 2019-08-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelrooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking/', verbose_name='Фото'),
        ),
    ]
